blank_issues_enabled: false
contact_links:
  - name: Question or Idea
    url: https://github.com/foxglove/studio/discussions
    about: Ask in our GitHub Discussions forum
  - name: Slack
    url: https://foxglove.dev/slack
    about: Get live help from the Foxglove Community
